### ISSUE TITLE
 Admin - Contact Summary Layout menu does not appear

### ISSUE THREAD

**Issue by privaterra** [civicrm/org.civicrm.contactsummary#4]
I have followed the steps mentioned in the readme to install. All the dependant extensions are installed, however when I navigate to the  Administer -> Customize Data and Screens I do not see the Contact Summary Layouts option.

My details are below:

<img width="355" alt="screen shot 2018-07-16 at 12 45 06 pm" src="https://user-images.githubusercontent.com/1276079/42772052-2d59ac6c-88f7-11e8-9bf0-cc71e1728ffa.png">

- CiviCRM version - 5.3.0.
- PHP version 7.0.30-1~dotdeb+8.1

```
Extensions
Job Log Management (biz.lcdservices.joblogmanagement) version 1.0.1
CiviCRM Export to Excel (ca.bidon.civiexportexcel) version 1.10
CiviCRM Report Error (ca.bidon.reporterror) version 3.1
CiviCRM Log Viewer (ca.civicrm.logviewer) version 1.1
TinyMCE (com.aghstrategies.tinymce) version 1.4
Calendar (com.agiliway.civicalendar) version 2.1.0
Activity iCalendar Feed (com.joineryhq.activityical) version 1.4
SparkPost / CiviCRM Integration (com.pesc.sparkpost) version 1.3.5
Relationship Report (de.systopia.relationreport) version 1.0
Extended Logging Reports (nz.co.fuzion.extendedloggingreports) version 1.0
ExtendedReport (nz.co.fuzion.extendedreport) version 3.5
Displays relationships in the contact summary (org.civicoop.relationship2summary) version 1.2
Template attachments (org.civicoop.templateattachments) version 1.3
Angular Profiles (org.civicrm.angularprofiles) version 4.7.31-1.1.2
API v4 (org.civicrm.api4) version 1.0
Contact Summary Editor (org.civicrm.contactsummary) version 1.0
CiviCRM Bootstrap theme (org.civicrm.shoreditch) version 0.1-alpha19
CSV Import Helper (uk.artfulrobot.civicrm.importhelper) version 1.1.8
```

**Comment by colemanw** [comment]
@privaterra I just fixed this yesterday. Please do the following:
* completely uninstall this extension
* update this extension and the api4 extension (`git pull`)
* reinstall this extension

The menu item should appear. Let me know :)

**Comment by privaterra** [comment]
@colemanw that did the trick. The menu now appears. Proceeding use it :)
